name: main_platform
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  animated_rating_stars: ^1.0.1
  animated_splash_screen: ^1.3.0
  auto_route: ^8.1.3
  cached_network_image: ^3.3.1
  chat_bubbles: ^1.5.0
  crypto: ^3.0.3
  device_preview: ^1.1.0
  dio: ^5.4.3+1
  dropdown_search: ^5.0.6
  easy_localization: ^3.0.6
  equatable: ^2.0.5
  excel: ^4.0.3
  file_picker: ^8.0.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_secure_storage: ^9.0.0
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  hive_flutter: ^1.1.0
  image_picker: ^1.0.7
  injectable: ^2.3.2
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  page_transition: ^2.1.0
  path_provider: ^2.0.15
  pretty_dio_logger: ^1.3.1
  readmore: ^3.0.0
  shared_preferences: ^2.2.3
  sizer: ^2.0.15
  socket_io_client: ^2.0.3+1
  url_strategy: ^0.2.0
  dotted_border: ^2.1.0

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  hive_generator: ^2.0.1
  injectable_generator: ^2.4.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/night/
    - assets/images/brand/

  fonts:
    - family: Alexandria
      fonts:
        - asset: fonts/alexandria/thin.ttf
          weight: 100
        - asset: fonts/alexandria/extra-light.ttf
          weight: 200
        - asset: fonts/alexandria/light.ttf
          weight: 300
        - asset: fonts/alexandria/regular.ttf
          weight: 400
        - asset: fonts/alexandria/medium.ttf
          weight: 500
        - asset: fonts/alexandria/semi-bold.ttf
          weight: 600
        - asset: fonts/alexandria/bold.ttf
          weight: 700
        - asset: fonts/alexandria/extra-bold.ttf
          weight: 800
        - asset: fonts/alexandria/black.ttf
          weight: 900
